#!/bin/bash
set -euxo pipefail

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Install key applications

## Install initial apps
apt-get update && apt-get install -y docker-compose-plugin make vim

# Run all applications (app, tracetest, jaeger, otel)
cd /
git clone https://github.com/kubeshop/pokeshop.git
cd /pokeshop
# Running twice as queue tends to fail on the first run
DETACHED=true make run || true
DETACHED=true make run || true
