#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

if test -f "~/getting-creative"; then
    echo "Congrats! Moving on to the next step"
    exit 0
fi

echo "Please wait to continue with the group. In the mean time, you are welcome to keep exploring!"
exit 99
